update mlflow/aml/azure-monitor metrics and huggingface model card generation example drafts

diff --git a/.github/workflows/arm-cmd-job-pytorch.yml b/.github/workflows/arm-cmd-job-pytorch.yml
--- a/.github/workflows/arm-cmd-job-pytorch.yml
+++ b/.github/workflows/arm-cmd-job-pytorch.yml
@@ -1,14 +1,16 @@
-name: ARM Quickstart
+name: ARM Pytorch Job
 on:
+  schedule:
+    - cron: '0 18 * * 5'
   push:
     branches:
       - main
     paths:
       - ".github/workflows/arm-cmd-job-pytorch.yml"
-      - ".cloud/azuredeployCmdJobPytorch.json"
+      - ".cloud/quickstart/azuredeployCmdJobPytorch.json"
   workflow_dispatch:
 jobs:
-  fine-tune:
+  deploy-template:
     runs-on: [self-hosted]
     steps:
       - name: Checkout repo code
@@ -17,4 +19,21 @@ jobs:
       - name: Deploy ARM template
         run: |
           az deployment group create --resource-group ${{secrets.AZURE_RESOURCE_GROUP}} --template-file ./azuredeployCmdJobPytorch.json --parameters workspaceName='${{secrets.AZUREML_WORKSPACE}}' jobName='${{github.RUN_ID}}'
-        working-directory: .cloud
+        working-directory: .cloud/quickstart
+
+      - name: Check ML job status
+        run: |
+          az ml job stream -n $${{github.RUN_ID}}
+          status=$(az ml job show -n ${{github.RUN_ID}} --query status -o tsv)
+          echo $status
+          if [[ $status == "Completed" ]]
+          then
+            echo "Job completed"
+          elif [[ $status ==  "Failed" ]]
+          then
+            echo "Job failed"
+            exit 1
+          else 
+            echo "Job status not failed or completed"
+            exit 2
+          fi
